services:
  index-treccovid-1-e5:
    build: ./index-ir_datasets-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=cord19/trec-covid/round1", "--save=1000"]


  index-treccovid-2-e5:
    build: ./index-ir_datasets-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=cord19/trec-covid/round2", "--save=1000"]
    depends_on:   
      index-treccovid-1-e5:
        condition: service_completed_successfully


  index-treccovid-3-e5:
    build: ./index-ir_datasets-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=cord19/trec-covid/round3", "--save=1000"]
    depends_on:   
      index-treccovid-2-e5:
        condition: service_completed_successfully


  index-treccovid-4-e5:
    build: ./index-ir_datasets-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=cord19/trec-covid/round4", "--save=1000"]
    depends_on:   
      index-treccovid-3-e5:
        condition: service_completed_successfully



  index-treccovid-5-e5:
    build: ./index-ir_datasets-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=cord19/trec-covid/round5", "--save=1000"]
    depends_on:   
      index-treccovid-4-e5:
        condition: service_completed_successfully


  # LongEval
  index-longeval-wt-e5:
    build: ./index-longeval-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=longeval-WT", "--save=1000"]
    depends_on:   
      index-longeval-wt-e5:
        condition: service_completed_successfully


  index-longeval-st-e5:
    build: ./index-longeval-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=longeval-ST", "--save=1000"]
    depends_on:   
      index-longeval-wt-e5:
        condition: service_completed_successfully


  index-longeval-lt-e5:
    build: ./index-longeval-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=longeval-LT", "--save=1000"]
    depends_on:   
      index-longeval-st-e5:
        condition: service_completed_successfully


  # TripClick
  index-tripclick-t1-e5:
    build: ./index-tripclick-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=tripclick/test/head-t1", "--save=1000", "--batch_size=150"]
    depends_on:   
      index-longeval-wt-e5:
        condition: service_completed_successfully


  index-tripclick-t2-e5:
    build: ./index-tripclick-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=tripclick/test/head-t2", "--save=1000", "--batch_size=150"]
    depends_on:   
      index-tripclick-t1-e5:
        condition: service_completed_successfully


  index-tripclick-t3-e5:
    build: ./index-tripclick-e5/
    volumes:
      - ../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--dataset=tripclick/test/head-t3", "--save=1000", "--batch_size=150"]
    depends_on:   
      index-tripclick-t2-e5:
        condition: service_completed_successfully